'use client'

import { useEffect } from 'react'
import { useCommentStore } from '../../store/useCommentStore'
import { Header } from '../../components/layout/Header'
import { Panel } from '../../components/ui/primitives'
import { ReplyFeed } from '../../components/replies/ReplyFeed'
import { ExtensionSyncButton } from '../../components/layout/ExtensionSyncButton'

/**
 * Replies received on extension-generated comments. Like /history this reads
 * the extension bridge's IndexedDB rather than Supabase.
 */
export default function RepliesPage() {
  const { replies, loadReplies } = useCommentStore()

  useEffect(() => {
    loadReplies()
  }, [loadReplies])

  return (
    <div>
      <Header
        title="Replies Received"
        description="Replies to comments generated by the extension, synced from this browser."
        action={<ExtensionSyncButton />}
      />

      <Panel className="overflow-hidden">
        <ReplyFeed replies={replies} />
      </Panel>
    </div>
  )
}
