'use client'

import { useEffect } from 'react'
import { useCommentStore } from '../../store/useCommentStore'
import { Header } from '../../components/layout/Header'
import { Panel } from '../../components/ui/primitives'
import { CommentTable } from '../../components/history/CommentTable'
import { FilterBar } from '../../components/history/FilterBar'
import { SearchBar } from '../../components/history/SearchBar'
import { ExtensionSyncButton } from '../../components/layout/ExtensionSyncButton'

/**
 * Extension-synced comment history. Unlike the rest of the console this reads
 * IndexedDB (populated by the extension bridge), not Supabase — it shows what a
 * single operator's browser has synced, which is why it sits outside the main
 * nav and is reachable from Monitoring.
 */
export default function HistoryPage() {
  const {
    comments,
    isLoading,
    selectedCategory,
    searchQuery,
    loadComments,
    deleteComment,
    setCategory,
    setSearchQuery,
  } = useCommentStore()

  useEffect(() => {
    loadComments()
  }, [loadComments])

  return (
    <div>
      <Header
        title="Comment History"
        description="Comments generated by the extension in this browser, synced into local IndexedDB."
        action={<ExtensionSyncButton />}
      />

      <div className="mb-5 flex flex-wrap items-center gap-4">
        <SearchBar value={searchQuery} onChange={setSearchQuery} />
        <FilterBar selected={selectedCategory} onChange={setCategory} />
        <span className="ml-auto font-mono text-xs text-muted-foreground">
          {isLoading ? 'Loading…' : `${comments.length} comment${comments.length === 1 ? '' : 's'}`}
        </span>
      </div>

      <Panel className="overflow-hidden px-4 py-2 md:px-0 md:py-0">
        <CommentTable comments={comments} onDelete={deleteComment} />
      </Panel>
    </div>
  )
}
